export const siteConfig = {
  name: "DRM Paris 2",
  fullName: "Depannage Rideau Metallique Paris 2",
  domain: "depannagerideau-metallique-paris-2.fr",
  url: "https://depannagerideau-metallique-paris-2.fr",
  phone: "09 72 12 41 41",
  phoneLink: "tel:+33972124141",
  email: "contact@depannagerideau-metallique-paris-2.fr",
  city: "Paris 2",
  citySlug: "paris-2",
  cityShort: "Paris",
  postalCode: "75002",
  department: "Paris",
  departmentCode: "75",
  region: "Ile-de-France",
  address: "Impasse des Peintres, 75002 Paris",
  geo: {
    latitude: 48.8687,
    longitude: 2.3412,
  },
  openingHours: "24h/24, 7j/7",
  experience: "25+",
  delai: "30",
  rating: "4.9",
  ratingCount: "5",
  interventions: "5000+",
};

export const services = [
  {
    id: "depannage",
    name: "Depannage",
    slug: "depannage-rideau-metallique",
    description: "Intervention urgence 24h/24 sur rideau metallique en panne",
    shortDescription: "Rideau bloque ? Intervention en moins de 30 minutes.",
  },
  {
    id: "installation",
    name: "Installation",
    slug: "installation-rideau-metallique",
    description: "Pose complete de rideaux metalliques neufs pour commerces et industriels",
    shortDescription: "Pose sur-mesure pour commerces, bureaux et entrepots.",
  },
  {
    id: "reparation",
    name: "Reparation",
    slug: "reparation-rideau-metallique",
    description: "Remise en etat de rideaux metalliques endommages",
    shortDescription: "Lames, moteur, axe, serrure : reparation garantie.",
  },
  {
    id: "motorisation",
    name: "Motorisation",
    slug: "motorisation-rideau-metallique",
    description: "Automatisation de rideaux metalliques manuels existants",
    shortDescription: "Passez a l'electrique avec Somfy, Simu ou Nice.",
  },
  {
    id: "deblocage",
    name: "Deblocage",
    slug: "deblocage-rideau-metallique",
    description: "Liberation urgente de rideaux metalliques coinces",
    shortDescription: "Rideau coince ? Liberation rapide sans degradation.",
  },
  {
    id: "entretien",
    name: "Entretien",
    slug: "entretien-rideau-metallique",
    description: "Maintenance preventive et contrats annuels",
    shortDescription: "Evitez les pannes avec un entretien regulier.",
  },
  {
    id: "fabrication",
    name: "Fabrication",
    slug: "fabrication-rideau-metallique",
    description: "Fabrication sur-mesure de rideaux metalliques",
    shortDescription: "Acier, aluminium, inox : fabrication aux dimensions exactes.",
  },
];

export const zones = [
  { name: "Paris 1er", slug: "paris-1er", postalCode: "75001", distance: "0.5 km" },
  { name: "Paris 3e", slug: "paris-3e", postalCode: "75003", distance: "0.8 km" },
  { name: "Paris 4e", slug: "paris-4e", postalCode: "75004", distance: "1 km" },
  { name: "Paris 5e", slug: "paris-5e", postalCode: "75005", distance: "1.5 km" },
  { name: "Paris 6e", slug: "paris-6e", postalCode: "75006", distance: "1.8 km" },
  { name: "Paris 7e", slug: "paris-7e", postalCode: "75007", distance: "2.5 km" },
  { name: "Paris 8e", slug: "paris-8e", postalCode: "75008", distance: "2 km" },
  { name: "Paris 9e", slug: "paris-9e", postalCode: "75009", distance: "1.2 km" },
  { name: "Paris 10e", slug: "paris-10e", postalCode: "75010", distance: "1.5 km" },
  { name: "Paris 11e", slug: "paris-11e", postalCode: "75011", distance: "2 km" },
  { name: "Paris 12e", slug: "paris-12e", postalCode: "75012", distance: "3 km" },
  { name: "Paris 13e", slug: "paris-13e", postalCode: "75013", distance: "3.5 km" },
  { name: "Paris 14e", slug: "paris-14e", postalCode: "75014", distance: "4 km" },
  { name: "Paris 15e", slug: "paris-15e", postalCode: "75015", distance: "4.5 km" },
  { name: "Paris 16e", slug: "paris-16e", postalCode: "75016", distance: "5 km" },
  { name: "Paris 17e", slug: "paris-17e", postalCode: "75017", distance: "3 km" },
  { name: "Paris 18e", slug: "paris-18e", postalCode: "75018", distance: "3.5 km" },
  { name: "Paris 19e", slug: "paris-19e", postalCode: "75019", distance: "4 km" },
  { name: "Paris 20e", slug: "paris-20e", postalCode: "75020", distance: "3.5 km" },
  { name: "Boulogne-Billancourt", slug: "boulogne-billancourt", postalCode: "92100", distance: "7 km" },
  { name: "Levallois-Perret", slug: "levallois-perret", postalCode: "92300", distance: "5 km" },
  { name: "Neuilly-sur-Seine", slug: "neuilly-sur-seine", postalCode: "92200", distance: "6 km" },
];

export const colors = {
  primary: "#1B4332",
  accent: "#C9A84C",
  accentLight: "#D4B96A",
  accentHover: "#B8963F",
  lightBg: "#F5F0E8",
  warmBg: "#FAF7F2",
  darkBg: "#0F2B21",
  darkVariant: "#143D2E",
  white: "#FFFFFF",
  textDark: "#1B4332",
  textMuted: "#555555",
  textLight: "rgba(255,255,255,0.6)",
  border: "#E5E5E5",
  starColor: "#F59E0B",
};

export const marques = [
  "Somfy", "Simu", "ACM", "Came", "Nice", "FAAC", "BFT", "Sommer",
];

export const tarifs = [
  { intervention: "Deblocage simple", prix: "149 - 350" },
  { intervention: "Reparation moteur", prix: "390 - 800" },
  { intervention: "Remplacement lames (3-5)", prix: "189 - 500" },
  { intervention: "Remplacement axe", prix: "400 - 900" },
  { intervention: "Remplacement ressort", prix: "220 - 450" },
  { intervention: "Motorisation complete", prix: "500 - 1 500" },
  { intervention: "Installation rideau neuf", prix: "800 - 5 000" },
  { intervention: "Contrat entretien annuel", prix: "250 - 500" },
];
